import type { Artist } from '@/domain';

/**
 * DEMO ARTISTS. These are not real people and not artists represented in the House of
 * Nucci Collection. They exist so the Artist Passport can be built and reviewed before
 * real records arrive. Names carry a visible "(Demo Artist)" suffix and every prose field
 * that would normally hold sourced biography is null, because inventing one is forbidden
 * (spec §25, §104).
 */
export const artists: Artist[] = [
  {
    id: 'artist-demo-vantage-field',
    slug: 'vantage-field',
    name: 'Vantage Field (Demo Artist)',
    overview: 'Demo artist record. Used to exercise the Artist Passport layout.',
    biography: null,
    whyInTheHouse: null,
    artistStatement: null,
    process: null,
    sources: [],
    exhibitions: [],
    press: [],
    talks: [],
    links: [],
    verification: 'unverified',
    portraitUrl: null,
    state: 'published',
    isPlaceholder: true,
  },
  {
    id: 'artist-demo-null-harbour',
    slug: 'null-harbour',
    name: 'Null Harbour (Demo Artist)',
    overview: 'Demo artist record. Used to exercise series grouping and edition display.',
    biography: null,
    whyInTheHouse: null,
    artistStatement: null,
    process: null,
    sources: [],
    exhibitions: [],
    press: [],
    talks: [],
    links: [],
    verification: 'unverified',
    portraitUrl: null,
    state: 'published',
    isPlaceholder: true,
  },
  {
    id: 'artist-demo-slow-concrete',
    slug: 'slow-concrete',
    name: 'Slow Concrete (Demo Artist)',
    overview: 'Demo artist record. Used to exercise moving-image presentation.',
    biography: null,
    whyInTheHouse: null,
    artistStatement: null,
    process: null,
    sources: [],
    exhibitions: [],
    press: [],
    talks: [],
    links: [],
    verification: 'unverified',
    portraitUrl: null,
    state: 'published',
    isPlaceholder: true,
  },
  {
    id: 'artist-demo-pixel-ordnance',
    slug: 'pixel-ordnance',
    name: 'Pixel Ordnance (Demo Artist)',
    overview: 'Demo artist record. Used to exercise nearest-neighbour pixel rendering.',
    biography: null,
    whyInTheHouse: null,
    artistStatement: null,
    process: null,
    sources: [],
    exhibitions: [],
    press: [],
    talks: [],
    links: [],
    verification: 'unverified',
    portraitUrl: null,
    state: 'published',
    isPlaceholder: true,
  },
  {
    id: 'artist-demo-glass-register',
    slug: 'glass-register',
    name: 'Glass Register (Demo Artist)',
    overview: 'Demo artist record. Used to exercise the vector / on-chain SVG renderer.',
    biography: null,
    whyInTheHouse: null,
    artistStatement: null,
    process: null,
    sources: [],
    exhibitions: [],
    press: [],
    talks: [],
    links: [],
    verification: 'unverified',
    portraitUrl: null,
    state: 'published',
    isPlaceholder: true,
  },
];
